# .gitpod.yml

# This file configures the Gitpod environment for your Simple Banking System project.

# Specify the Docker image to use for the workspace.
# This image comes with Java 17 and other common development tools.
image: gitpod/workspace-java-17

# Commands to run when the workspace starts.
# This ensures your Java files are compiled automatically.
tasks:
  - name: Compile Banking System
    command: |-
      javac *.java
    # No ports to open for a console application
    openPorts: []

# VS Code extensions to install (optional, but highly recommended for a better experience)
# These extensions provide Java language support, debugging, and testing features.
vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
