image: gitpod/workspace-java-17

tasks:
  - name: Compile Banking System
    command: |-
      javac *.java
    openPorts: []

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
